name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: stylua
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Stylua Format
        uses: JohnnyMorganz/stylua-action@v3
        with:
          version: 0.17.1
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua/
